[versions]
accompanistNavigationAnimation = "0.36.0"
agp = "8.13.0"
blurview = "version-3.1.0"
coilCompose = "2.7.0"
coilTransformations = "2.4.0"
datastorePreferences = "1.1.7"
dec = "0.1.2"
exoplayerCore = "2.19.1"
exoplayerProgressive = "2.19.1"
exoplayerUi = "2.19.1"
extensionFfmpeg = "2.20.0"
gson = "2.13.1"
hazeJetpackCompose = "0.7.0"
kotlin = "2.2.0"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
kotlinxSerializationJson = "1.9.0"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"

compose-bom = "2025.08.00"
activity-compose = "1.10.1"
materialColorUtilities = "1.3.0"
materialColorUtilitiesAndroid = "3.0.1"
materialKolor = "3.0.1"
media = "1.7.0"
media3Datasource = "1.8.0"
media3DatasourceOkhttp = "1.8.0"
media3Exoplayer = "1.8.0"
navigation = "2.9.3"
lifecycle = "2.9.2"
okhttp = "5.1.0"
paletteKtx = "1.0.0"
reorderable = "0.9.6"
foundationLayout = "1.9.0"
securityCrypto = "1.1.0"
uiGraphics = "1.9.0"
workRuntimeKtx = "2.11.0"

[libraries]
accompanist-navigation-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanistNavigationAnimation" }
androidx-animation = { module = "androidx.compose.animation:animation" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-media = { module = "androidx.media:media", version.ref = "media" }
androidx-media3-datasource-okhttp = { module = "androidx.media3:media3-datasource-okhttp", version.ref = "media3DatasourceOkhttp" }
androidx-media3-datasource = { module = "androidx.media3:media3-datasource", version.ref = "media3Datasource" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Exoplayer" }
androidx-palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "paletteKtx" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "uiGraphics" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
blurview = { module = "com.github.Dimezis:BlurView", version.ref = "blurview" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
dec = { module = "org.brotli:dec", version.ref = "dec" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
haze-jetpack-compose = { module = "dev.chrisbanes.haze:haze-jetpack-compose", version.ref = "hazeJetpackCompose" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

# Compose
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-icons = { module = "androidx.compose.material:material-icons-extended" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
material-color-utilities-android = { module = "com.materialkolor:material-color-utilities-android", version.ref = "materialColorUtilitiesAndroid" }
material-kolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
reorderable = { module = "org.burnoutcrew.composereorderable:reorderable", version.ref = "reorderable" }
androidx-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "foundationLayout" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android      = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose      = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
